export const tools = [
  {
    id: 1,
    name: "Metaboost CSV generator",
    url: "https://metaboost.vercel.app/",
    image: "/images/tools/metaboost.png",
    btn: "Visit website",
    label: "New",
  },
  {
    id: 2,
    name: "Adobe Stock Title Scrapper",
    url: "https://wasi-adobe.vercel.app/",
    image: "/images/tools/adobe.jpg",
    btn: "Visit website",
    label: "New",
  },
  {
    id: 3,
    name: "Snapchat Video Downloader",
    url: "https://snapscrapper.vercel.app/",
    image: "/images/tools/snap.jpg",
    btn: "Visit website",
    label: "Exclusive",
  },
  {
    id: 4,
    name: "Recraft AI Automation Tool",
    url: "https://thisnaeem.netlify.app",
    image: "/images/tools/re.jpg",
    btn: "Visit website",
    label: "New",
  },
  {
    id: 5,
    name: "Metaboost",
    url: "https://metaboost.vercel.app/",
    image: "/images/tools/metaboost.png",
    btn: "Visit website",
    label: "New",
  },
];
